In [5]:
import numpy as np
data = np.random.random((100,5))
np.savetxt("dados.csv",data,fmt='%.2f',delimiter=',',header="c1,c2,c3,c4,c5")


In [8]:
partecsv = np.loadtxt("./dados.csv", delimiter=",")
print(partecsv[:5, :])

[[0.35 0.17 0.04 0.37 0.34]
 [0.42 0.48 0.5  0.38 0.59]
 [0.77 0.88 0.34 0.7  0.31]
 [0.03 0.05 0.27 0.2  0.77]
 [0.29 0.76 0.01 0.9  0.1 ]]


In [9]:
import pandas as pd
df = pd.read_csv("dados.csv")
df

# c1    c2    c3    c4    c5
0   0.35  0.17  0.04  0.37  0.34
1   0.42  0.48  0.50  0.38  0.59
2   0.77  0.88  0.34  0.70  0.31
3   0.03  0.05  0.27  0.20  0.77
4   0.29  0.76  0.01  0.90  0.10
..   ...   ...   ...   ...   ...
95  0.20  0.00  0.05  0.90  0.85
96  0.16  0.07  0.90  0.37  0.18
97  0.32  0.75  0.85  0.29  0.07
98  0.55  0.36  0.89  0.11  0.17
99  0.99  0.80  0.42  0.15  0.67

[100 rows x 5 columns]

In [ ]:
#pip install openpyxl
df.to_excel("dadosExcel.xlsx")